name: SSH Connection Test

on:
  push:
    branches:
      - Dev  # Trigger on pushes to the Dev branch

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Ensure Temporary Directory on Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p /tmp/laravel-timr"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Fresh Code to Temporary Directory on Server
        run: |
          # Define the source directory path
          SOURCE_DIR="${GITHUB_WORKSPACE}/"
          
          # Copy files to the temporary directory on the server
          scp -r -v "$SOURCE_DIR" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/laravel-timr/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Manage Directories on Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            # Check if the backup directory exists and delete it if it does
            if [ -d ~/bu_laravel_timr ]; then
              sudo rm -rf ~/bu_laravel_timr
            fi

            # Backup the current Laravel directory
            if [ -d /var/www/laravel-timr ]; then
              sudo mv /var/www/laravel-timr ~/bu_laravel_timr
            fi

            # Create a new directory for the updated application
            sudo mkdir -p /var/www/laravel-timr

            # Set permissions
            sudo chown -R www-data:www-data /var/www/laravel-timr
            sudo chmod -R 755 /var/www/laravel-timr
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Move Code from Temporary Directory to Target Directory
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            sudo mv /tmp/laravel-timr/Timr/* /var/www/laravel-timr/
            sudo chown -R www-data:www-data /var/www/laravel-timr
            sudo chmod -R 755 /var/www/laravel-timr
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Composer Dependencies
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /var/www/laravel-timr
            sudo composer install --no-interaction
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Restart Apache2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo systemctl restart apache2"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
