name: Deploy Laravel Application

on:
  push:
    branches:
      - Dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Code
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            sudo rm -rf /var/www/laravel-timr
            sudo mkdir -p /var/www/laravel-timr
            sudo chown -R www-data:www-data /var/www/laravel-timr
            sudo chmod -R 755 /var/www/laravel-timr
            sudo mv /tmp/laravel-timr/Timr/* /var/www/laravel-timr/
            sudo cp /var/www/bu_laravel-timr/.env /var/www/laravel-timr/
            sudo mkdir -p /var/www/laravel-timr/bootstrap/cache
            sudo chown -R www-data:www-data /var/www/laravel-timr/storage /var/www/laravel-timr/bootstrap/cache
            sudo chmod -R 775 /var/www/laravel-timr/bootstrap/cache
            cd /var/www/laravel-timr
            sudo -u www-data composer install --no-interaction
            sudo -u www-data php artisan key:generate
            sudo -u www-data php artisan cache:clear
            sudo -u www-data php artisan config:cache
            sudo -u www-data php artisan route:cache
            sudo -u www-data php artisan view:clear
            sudo -u www-data php artisan optimize
            sudo -u www-data composer dump-autoload
            sudo systemctl restart apache2
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
